name: Publish Crate and Create GitHub Release

on:
  workflow_dispatch:

permissions: {}

jobs:
  release:
    name: Tag, Publish Crate, and Create GitHub Release
    runs-on: ubuntu-24.04
    if: ${{ github.repository_owner == 'chege' }}
    environment: release
    permissions:
      contents: read
      id-token: write # Required for trusted publishing
    steps:
      - &checkout
        name: Checkout repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - &setup-rust
        name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9
        with:
          toolchain: stable
      # Generating a GitHub token, so that PRs and tags created by
      # the release-plz-action can trigger actions workflows.
      - name: Generate GitHub token
        uses: actions/create-github-app-token@7e473efe3cb98aa54f8d4bac15400b15fad77d94 # v2.2.0
        id: generate-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          # pull-requests permission is not needed for the `release` command, so restricting it to contents only
          permission-contents: write
      - name: Run `release-plz release`
        uses: release-plz/action@d529f731ae3e89610ada96eda34e5c6ba3b12214 # v0.5.118
        with:
          command: release
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
