name: Publish Crate and Create GitHub Release

on:
  workflow_dispatch:

permissions: {}

jobs:
  release:
    name: Tag, Publish Crate, and Create GitHub Release
    runs-on: ubuntu-24.04
    if: ${{ github.repository_owner == 'chege' }}
    environment: release
    permissions:
      contents: read
      id-token: write # Required for trusted publishing
    steps:
      - &checkout
        name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v5.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - &setup-rust
        name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9
        with:
          toolchain: stable
      # Generating a GitHub token, so that PRs and tags created by
      # the release-plz-action can trigger actions workflows.
      - name: Generate GitHub token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        id: generate-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          # pull-requests permission is not needed for the `release` command, so restricting it to contents only
          permission-contents: write
      - name: Run `release-plz release`
        uses: release-plz/action@487eb7b5c085a664d5c5ca05f4159bd9b591182a # v0.5.120
        with:
          command: release
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
