name: Weekly Sanity Check

on:
  schedule:
    - cron: '0 4 * * 1' # Every Monday 04:00 UTC
  workflow_dispatch:

jobs:
  sanity-check-matrix:
    name: Download Crate and Run Sanity Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v6.0.0
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Run sanity tests
        run: |
          cd sanity
          cargo test --all-features --quiet